# Generated by Django 5.0.3 on 2024-03-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2_app2_article_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_stamp_create', models.DateTimeField()),
                ('time_stamp_modify', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2_app2_article_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2_app2_article_app.author')),
            ],
        ),
    ]
