# Generated by Django 5.0.3 on 2024-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Орёл', 'Орёл'), ('Решка', 'Решка')], max_length=5)),
                ('throw_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
